name: Go

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      HOST: localhost
      PORT: 5432
      USER: root
      PASSWORD: root
      DB_NAME: root
    strategy:
      matrix:
        go_version: ['1.18', '1.17', '1.21', '1.22']
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}
      
    - name: Install docker-ompose
      run: |
        export PATH=$PATH:/usr/local/bin
        curl -SL "https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-linux" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
    
    - name: Test docker-compose
      run: /usr/local/bin/docker-compose --version

    - name: Build-DB
      run: docker-compose -f docker-compose.yml build
      
    - name: Create-DB
      run: docker-compose up -d

    - name: Test
      run: go test -v main_test.go 
      
  
  build:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-22.04']
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go
